name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 或者你的主分支名称

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'

    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        git checkout gh-pages || git checkout -b gh-pages
        git merge main --allow-unrelated-histories
        git push origin gh-pages

    - name: Update GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PAT }}
        publish_dir: .
        force_orphan: true
